### ISSUE TITLE
placeholderImageUri working on Android, but not on iOS

### ISSUE THREAD

**Issue by MrSnoozles** [nativescript-community/ui-image#35]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
The attribute `placeholderImageUri` seems to be working on Android but not on iOS. The image is just blank until the real image `src` is loaded. **An example repository is provided.**

### Which platform(s) does your issue occur on?
- iOS only
- iOS 13.6.1
- iPhone 6s

### Please, provide the following version numbers that your issue occurs with:

- CLI: 7.0.11
- Cross-platform modules: 7.0.13
- Plugin(s): 
  - "@nativescript-community/ui-image": "4.0.17",

### Please, tell us how to recreate the issue in as much detail as possible. 
- git clone https://github.com/MrSnoozles/nsc-image-placeholder
- npm install
- npm run ios --no-hmr

### Is there any code involved? 
- https://github.com/MrSnoozles/nsc-image-placeholder/blob/master/app/components/Home.vue#L12

### Additional info

I thought this might be related to #12 but the issue there is on Android with Angular. Android (with Vue.JS) is working as expected for me.

### Screenshot

On Android a placeholder will be shown until the image is loaded. On iOS the screen is blank until the image is loaded.

![nsimage-placeholder](https://user-images.githubusercontent.com/17496592/101463342-932e3780-393d-11eb-947b-e4afe801faf6.jpg)

**Comment by farfromrefug** [comment]
@MrSnoozles should be fixed in 4.0.18 can you try?

**Comment by MrSnoozles** [comment]
Tried it and unless I did something wrong it's not yet working.

I `npm update`d and confirmed the package.json in `node_modules/@nativescript-community/ui-image` is at 4.0.18. I then removed the ios platform and ran `ns run ios --no-hmr` again. I unfortunately still don't see the placeholder image.

**Comment by farfromrefug** [comment]
@MrSnoozles i have tested your example and sadly i dont know why but N `ImageSource.fromFileSync` returns null while the path is right. Dont really have the time right now to look further. But the issue does not seem to be on the plugin side.
